---
name: maginx
version: 2
handle:
  - rewrite: if( path ~ "^/(js|css|images|media)(.*)$" ) goto "/web/$1$2?p=/%{QUERY_STRING}"
  - rewrite: if( query_string !~ "^p=/" && path ~ "^([\w-_/]*/)?(\w*)" ) goto "/web/index.php?p=/$1&a=$2&%{QUERY_STRING}"
  - rewrite: if( path !~ "^/web" ) goto "/web/404.html"
  - errordoc: 404 /web/404.html
